//
// Created by Tim on 16/06/2020.
//

#ifndef EMBEDDED_UTILITY_LIBRARY_LOGLEVELS_H
#define EMBEDDED_UTILITY_LIBRARY_LOGLEVELS_H

#define LOG_LEVEL_TRACE 5
#define LOG_LEVEL_DEBUG 4
#define LOG_LEVEL_INFO 3
#define LOG_LEVEL_WARN 2
#define LOG_LEVEL_ERROR 1
#define LOG_LEVEL_DISABLED 0

#endif //EMBEDDED_UTILITY_LIBRARY_LOGLEVELS_H
