//
// Created by Tim on 16/06/2020.
//

#ifndef EMBEDDED_UTILITY_LIBRARY_USART_INTERNAL_H
#define EMBEDDED_UTILITY_LIBRARY_USART_INTERNAL_H

#ifdef __AVR_ATmega328P__

#define USART_BUFFER_SIZE 32
#define USART_BUFFER_INDEX_MAX_VALUE 255

#define USART_BAUD_RATE_REGISTER_L UBRR0L
#define USART_BAUD_RATE_REGISTER_H UBRR0H
#define USART_CONTROL_STATUS_REGISTER_A UCSR0A
#define USART_CONTROL_STATUS_REGISTER_B UCSR0B
#define USART_CONTROL_STATUS_REGISTER_C UCSR0C
#define USART_DATA_REGISTER UDR0

#define USART_DATA_REGISTER_EMPTY UDRE0
#define USART_RX_ENABLE RXEN0
#define USART_RX_INTERRUPT_ENABLE RXCIE0
#define USART_TX_ENABLE TXEN0
#define USART_TX_INTERRUPT_ENABLE TXCIE0

#endif

#endif //EMBEDDED_UTILITY_LIBRARY_USART_INTERNAL_H
