//
// Created by timti on 03/03/2021.
//

#ifndef EMBEDDED_UTILITY_LIBRARY_PINS_ATMEGA328P_H
#define EMBEDDED_UTILITY_LIBRARY_ATMEGA328P_H

#define USART_COUNT 1

#endif //EMBEDDED_UTILITY_LIBRARY_PINS_ATMEGA328P_H
