//
// Created by timti on 03/03/2021.
//

#ifndef EMBEDDED_UTILITY_LIBRARY_PINS_ATMEGA2560_H
#define EMBEDDED_UTILITY_LIBRARY_ATMEGA2560_H

#define USART_COUNT 4

#endif //EMBEDDED_UTILITY_LIBRARY_PINS_ATMEGA2560_H
