//
// Created by timti on 27/05/2021.
//

#ifndef EMBEDDED_UTILITY_LIBRARY_STATE_MACHINE_TEST_H
#define EMBEDDED_UTILITY_LIBRARY_STATE_MACHINE_TEST_H


void stateMachineTest();


#endif //EMBEDDED_UTILITY_LIBRARY_STATE_MACHINE_TEST_H
